### ISSUE TITLE
Optimization opportunities identified which will be visited later

### ISSUE THREAD

**Issue by richajaindce** [private-attribution/ipa#101]
This issue aims to document all the possible optimization opportunities which were identified during coding. In a near future, when we are working on making the code optimal, these can be used as a checklist.

**Comment by richajaindce** [comment]
1. As discussed in #97, in the function apply_inv for now, we are using Permutation crate tp implement `apply_inv` and `apply` functions. However this uses usize which is either 32-bit or 64-bit depending on the architecture we are using. In our case, if we are sorting less than 2^32 elements (over 4 billion) 32-bits is sufficient. We probably never need a 64-bit number and is not optimal. It would even be cool to use a u16 if you're sorting less than 65,000 items. In future, we should plan to change this code to use u32 or u16 based on number of items

**Comment by akoshelev** [comment]
@richajaindce Given that we are not planning any investments in the old shuffle protocol, should we close this issue?

**Comment by richajaindce** [comment]
We can close this but it is possible that we might use this shuffle (as we discussed in Friday meeting right?).
