### ISSUE TITLE
test_complex_circuit_dzkp takes more than 60 seconds to finish

### ISSUE THREAD

**Issue by akoshelev** [private-attribution/ipa#1024]
I am observing some long running prop tests inside the newly implemented module for distributed zero-knowledge proofs

```
cargo test
...
test protocol::context::dzkp_validator::tests::test_complex_circuit_dzkp has been running for over 60 seconds
...
test result: ok. 636 passed; 0 failed; 5 ignored; 0 measured; 0 filtered out; finished in 136.89s

```

We need to avoid having those in our approval workflow that we run locally many times a day. If this test really needs that much data to explore, consider moving it to Github CI

**Comment by danielmasny** [comment]
https://github.com/private-attribution/ipa/pull/1027
