### ISSUE TITLE
PRSS validation in debug runs

### ISSUE THREAD

**Issue by akoshelev** [private-attribution/ipa#113]
Currently we have `Participant` interface that provides the entry point into shared randomness generation. Clients can request a dedicated space of randomess (basically a PRF with the fixed key) from `Participant` by using an index value. There is currently no enforcement for this index to be unique.

It is easy to make a mistake right now and incorrectly implement `SpaceIndex` for a given step and create security violations in IPA code. 

This issue is to discuss what can be done to avert that. Can we create a proc macro that can implement `SpaceIndex` for any enum? Is it possible to use Bloom filters to validate values generated by all PRSS instances in end-to-end tests and alert when program generates the same value for the same index?

**Comment by martinthomson** [comment]
We managed to fix this in #208.
