### ISSUE TITLE
Increasing number of bits in histogram values from 16 to 32 increases IPA latency by as much as 50%

### ISSUE THREAD

**Issue by akoshelev** [private-attribution/ipa#1151]
This is a tracking issue to understand why the impact is so significant. For 50M runs with the current event generator, aggregating all trigger values sums up to 400k (2^19), so we really use just 4 more bits and we shouldn't see performance regressions of that scale

**Comment by akoshelev** [comment]
1M run (16 bits): https://draft-mpc.vercel.app/query/view/meet-alarm2024-06-18T2026. 10m 28s.
1M run (32 bits): https://draft-mpc.vercel.app/query/view/vocal-wet2024-06-18T2043. 10m 23s

as expected it does not have any impact on small runs

**Comment by andyleiserson** [comment]
Here's the calculation of the number of multiplies (which I think is also indicative of the circuit depth): https://docs.google.com/spreadsheets/d/1A55vv7TaIVMP7Nf9ZxZqzkKGjFun2AA2N-lMzb6Kga4/edit#gid=0

I'm wondering if it's something like the number of tokio polls or context switches scaling with the number of outputs bits, even if the amount or work to do doesn't.

**Comment by akoshelev** [comment]
20M run (16 bits): https://draft-mpc.vercel.app/query/view/tried-goth2024-06-18T2054. 11376.323407524s
20M run (32 bits): https://draft-mpc.vercel.app/query/view/brute-joint2024-06-19T0032. (pending)

**Comment by akoshelev** [comment]
> Here's the calculation of the number of multiplies (which I think is also indicative of the circuit depth): https://docs.google.com/spreadsheets/d/1A55vv7TaIVMP7Nf9ZxZqzkKGjFun2AA2N-lMzb6Kga4/edit#gid=0
> 
> I'm wondering if it's something like the number of tokio polls or context switches scaling with the number of outputs bits, even if the amount or work to do doesn't.

![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExaGgyeHB3MDJ5d2d6emw1OHN3a3hjOGw5azFpN2ExejhnNjE4c3k3NCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/4Hx5nJBfi8FzFWxztb/giphy.gif)

**Comment by akoshelev** [comment]
ok, so for 20M events there is actually no difference in performance. Histogram values were hovering around 418896

**Comment by akoshelev** [comment]
I am going to test 40M now

40M run (16 bits): https://draft-mpc.vercel.app/query/view/macro-voter2024-06-19T0559 (pending)

**Comment by akoshelev** [comment]
50M run (16 bits); https://draft-mpc.vercel.app/query/view/dizzy-mop2024-06-20T1718 (pending)

**Comment by akoshelev** [comment]
100M run (16 bits): https://draft-mpc.vercel.app/query/view/vast-rink2024-06-22T0528 (pending)

**Comment by akoshelev** [comment]
I want to push fixes for #1141 first and then validate that there is no impact on 100M rows before closing this

**Comment by akoshelev** [comment]
#1141 is fixed now, doing another 100M run: https://draft-mpc.vercel.app/query/view/black-baton2024-07-10T1650

**Comment by akoshelev** [comment]
100M run (16 bits): https://draft-mpc.vercel.app/query/view/black-baton2024-07-10T1650 (50305.268764835s)
100M run (32 bits): https://draft-mpc.vercel.app/query/view/terse-altar2024-07-11T2315 (pending)

**Comment by akoshelev** [comment]
32 bit run crashed because there was already another query running. trying again

**Comment by akoshelev** [comment]
https://draft-mpc.vercel.app/query/view/solid-calm2024-07-12T1954

**Comment by akoshelev** [comment]
No regression is detected, closing this issue
