### ISSUE TITLE
Malicious IPA stalls with non-relaxed DP parameters

### ISSUE THREAD

**Issue by akoshelev** [private-attribution/ipa#1298]
[Here](https://draft-mpc.vercel.app/query/view/exact-alley2024-09-20T2245) is a draft run that reproduces the issue. It seems similar to stalls we're observing in aggregation where `validate_record` requires all futures to be spawned in order to make progress. Instead we're getting one future at a time and we stall.

Non relaxed DP generates more records, making it more likely to hit the stall issue. @danielmasny is currently looking for a place inside DP generation where it could be happening

**Comment by andyleiserson** [comment]
I believe this is a duplicate of #1300.
