### ISSUE TITLE
Malicious IPA with DP stalls on 10 record input

### ISSUE THREAD

**Issue by danielmasny** [private-attribution/ipa#1300]
We've identified a few issues here. Correctness is the first one:

When we compute `read_size` inside Infra, we set it this way

```rust
     std::cmp::min(
                    total_capacity,
                    // closest multiple of record_size to read_size
                    gateway_config.read_size.get() / record_size * record_size,
                )
```

the value used in config is `2048`. For PRF evaluations, record size is set to 512 (Vectorization factor of 16 for 32 byte records). This means, `read_size` is 4 records. For inputs that are not a multiple of 4, PRF will stall because `active_work` is set to minimum of input size or 32k. 

For example, input size 10 will trigger sends for first two batches and then everything will hang because third batch will be half full. `validate_record` blocks the futures inside the seq_join until we resolve 10, but we could only resolve 8.  

The proper fix would be to account for `total_records` when computing `read_size`. 

Another issue is performance. When adding dummies to small inputs, we significantly increase the total number of records processed by the protocol, but we never adjust the active work. If we add 600 dummies to 5 row input, our active work would be still 5.

**Comment by andyleiserson** [comment]
Any objections to closing this?

**Comment by akoshelev** [comment]
Let me capture the active work problem separately and this one can be closed
