### ISSUE TITLE
Expand definition of `Network` layer into `Transport` layer

### ISSUE THREAD

**Issue by thurstonsand** [private-attribution/ipa#352]
We currently have the concept of a `Network` layer that handles the communication between helpers. It interacts directly with the Infra layer to move data for running protocols.

the `Network` trait currently looks like this:

```rust
/// Network interface for components that require communication.
pub trait Network: Sync {
    /// Type of the channel that is used to send/receive messages to/from other helpers
    type Sink: futures::Sink<MessageChunks, Error = Error> + Send + Unpin + 'static;
    type MessageStream: Stream<Item = MessageChunks> + Send + Unpin + 'static;

    /// Returns a sink that accepts data to be sent to other helper parties.
    fn sink(&self) -> Self::Sink;

    /// Returns a stream to receive messages that have arrived from other helpers. Note that
    /// some implementations may panic if this method is called more than once.
    fn recv_stream(&self) -> Self::MessageStream;
}
```

there's a way to "send" data to another helper via the `sink()`, and "receive" data from the other helpers via the `recv_stream`. This works for an actively running query, but we don't have a way for helpers to communicate to each other about _starting_ queries.

Here's how that workflow would look, in short:

* Report Collector wants to start a new query on data that it has
* Report Collector calls an externally available "Create Query" API to one of the helpers
* That helper becomes the de facto "leader" of the request, generates a query id, and sends a "Prepare Query" message to the "follower" helpers; then, it tells the Report Collector what the new query id is
* Report Collector sends all its data to the leader using a "Send Data" API
* Leader disseminates that data to the 2 followers, then they all coordinate starting the protocol at the same time

So there is a mix of externally available APIs to initiate queries, as well as helper-to-helper communication that needs to happen before a query is even started. All of this communication should be abstracted such that it could be implemented for HTTP, InMemory, maybe protobuf, or anything else. For that, I want to propose a new trait, `Transport`:

```rust
pub trait Transport: Sync {
    type CommandStream: Stream<Item = TransportCommand> + Send + Unpin + 'static;
    type Sink: futures::Sink<TransportCommand, Error = TransportError> + Send + Unpin + 'static;

    /// To be called by an entity which will handle the events as indicated by the
    /// [`SubscriptionType`]. There should be only 1 subscriber per type.
    /// # Panics
    /// May panic if attempt to subscribe to the same [`SubscriptionType`] twice
    fn subscribe(&self, subscription_type: SubscriptionType) -> Self::CommandStream;

    /// To be called when an entity wants to send commands to the `Transport`.
    async fn send(&self, command: TransportCommand) -> Result<(), TransportError>;
}
```

The primary difference from the old `Network` trait is the idea of a `TransportCommand`. instead of _just_ `MessageChunks`, you can send a command, which is defined as an enum of all possible actions a `Transport` might want to make. That would include commands like `CreateQuery`, `PrepareQuery`, `SendData`, `StartProtocol`, etc.

It would also include `NetworkEvent`, which contains `MessageChunks`, and would be the command used to cover the functionality the old `Network` provided, which I talk more about below.

The `Transport` trait simply exposes a `subscribe` function that allows you to receive a `Stream` of incoming commands, and a `send`, which allows you to send commands.

The last piece to discuss is the `SubscriptionType` (as part of the `subscribe` method), and to talk about how the `Transport` interacts with the infra layer. Under the existing implementation, the infra used the `Network` to grab a `Sink` and `Stream` to send/receive data with. In order to minimize the impact/number of changes on infra, I'm also proposing a new `Network` struct that would take its place. It would still deal in `MessageChunks` exclusively, and would look as follows:

```rust
/// Given any implementation of [`Transport`], a `Network` is able to send and receive 
/// [`MessageChunks`] for a specific query id. The [`Transport`] will receive `NetworkEvents` 
/// containing the `MessageChunks`
pub struct Network<T> {
    transport: T,
    query_id: QueryId,
}
```
with functions:
```rust
impl<T: Transport> Network<T> {
    /// sends a [`NetworkEvent`] containing [`MessageChunks`] on the underlying [`Transport`]
    pub async fn send(&self, message_chunks: MessageChunks) -> Result<(), Error>;

    /// returns a [`Stream`] of [`MessageChunks`]s from the underlying [`Transport`]
    /// # Panics
    /// if called more than once during the execution of a query.
    pub fn recv_stream(&self) -> impl Stream<Item = MessageChunks>;
```
So the major differences are
* This is a struct, not a trait
* Instead of a `Sink`, infra would use the `send` function

Hopefully, this would act as an almost-drop-in replacement of existing `Network` for infra.

Finally, returning to `SubscriptionType`, this has 2 options:
```rust
/// Users of a [`Transport`] must subscribe to a specific type of command, and so must pass this
/// type as argument to the `subscribe` function
pub enum SubscriptionType {
    /// Commands for managing queries
    Administration,
    /// Commands intended for a running query
    Query(QueryId),
}
```
So the administration piece (we are working on this in parallel) would subscribe to `Administration` commands, and the `Network` struct would use the `Query` subscription type to only subscribe to commands for a particular running query.

Feedback/ideas/improvements would be appreciated

**Comment by akoshelev** [comment]
A very rough sketch on interaction between layers that may provide some context why we need an additional layer from the network side.


![Network](https://user-images.githubusercontent.com/1110516/208540377-5338c639-06a8-4230-b1b7-dfe7a6287be1.png)

**Comment by martinthomson** [comment]
In Alex's picture, you have the transport operating at the level of IP addresses (or domain names, I suppose).   Is that right?  Can you have that layer understand another sort of identity instead?  Perhaps a configured name for each of the hosts that are involved.  Though role is assigned, you might need to bundle a bunch of things against hosts in config: address, keys, etc...

**Comment by martinthomson** [comment]
That sounds right, yep.

**Comment by akoshelev** [comment]
We can close this issue now
