### ISSUE TITLE
Update HPKE encryption of matchkeys according to the latest spec

### ISSUE THREAD

**Issue by akoshelev** [private-attribution/ipa#593]
https://github.com/patcg-individual-drafts/ipa/pull/56 asks us to authenticate match key encryption with trigger bit, which we don't do currently. 

The entry point into match key encryption is [`hpke`](https://github.com/private-attribution/ipa/tree/main/src/hpke) module.

* First thing that must be updated is the HPKE Info struct that must now carry a trigger event indicator. I am not a huge fan of boolean values, but we don't have an enum for event type (yet), so it is probably the right time to add it.

https://github.com/private-attribution/ipa/blob/cc48eba6c6ac967b3860e06cb895e3adcbfeeaa8/src/hpke/info.rs#L16

* `into_bytes` method of `Info` struct must correctly serialize this indicator as a single byte integer, according to the spec. 

https://github.com/private-attribution/ipa/blob/cc48eba6c6ac967b3860e06cb895e3adcbfeeaa8/src/hpke/info.rs#L76

After this, we need to update unit tests and property tests to validate the new AAD tag implementation. 

* `seal` and `open` test methods must take trigger/source event indicator as an parameter

https://github.com/private-attribution/ipa/blob/bc2e7e12d9c24eed454c2c8bda3f955dc845e135/src/hpke/mod.rs#L197 
https://github.com/private-attribution/ipa/blob/bc2e7e12d9c24eed454c2c8bda3f955dc845e135/src/hpke/mod.rs#L214

* update all unit tests to use the new signature of `seal` and `open`
* update `ipa_info_serialize` test to validate that binary format of `Info` includes trigger byte
* update `arbitrary_info_corruption` test to validate that decryption fails if source event is camouflaged as trigger

@martinthomson the `Info` struct now represents a single event context because of this trigger bit. I don't think it is a big deal because we can make it cheaply cloneable, so we can follow up on that. @bmcase wants to get his hands dirty with Rust, so this may be a good issue for him to get familiar with our code base.

**Comment by martinthomson** [comment]
Surely we can reuse `Info` for all events that share a site, epoch, keyid, and source/trigger bit.

**Comment by bmcase** [comment]
Created a PR to be reviewed, @akoshelev  https://github.com/private-attribution/ipa/pull/598

**Comment by akoshelev** [comment]
fixed in #598
