### ISSUE TITLE
Integration tests should pick available ports for helpers

### ISSUE THREAD

**Issue by akoshelev** [private-attribution/ipa#648]
> this is a bit annoying - I know that there is no guaranteed way to pick an available port (at least on MacOS, on Linux it works pretty reliable with SO_REUSEPORT and rust appears to be using [it](https://github.com/rust-lang-nursery/rust-cookbook/issues/500)), but even best-effort approach with TcpListener should work here. Right now it is not possible to test this in parallel

_Originally posted by @akoshelev in https://github.com/private-attribution/ipa/pull/647#discussion_r1192888175_

**Comment by martinthomson** [comment]
Andy [suggests](https://github.com/private-attribution/ipa/pull/647#discussion_r1193039179):

> I thought about this when I wrote the test... a possible strategy I came up with is to create `TcpListeners` in the test, pass them to the helper processes as /dev/stdin, and add an option to the helper that does `TcpListener::from_raw_fd` rather than bind a socket. I didn't do this at the time because it seemed like a fair amount of work, and it seemed useful to have at least one test that exercises the standard flow for binding the socket on startup. But if we're adding more tests that follow this framework, it becomes more important to do this work. I'll see if I can get this done next week.

It might be easier to do this instead: Have the server choose an ephemeral port and then write the resulting number to stdout.  Then the runner can read stdout from the spawned process until it reads off the port number and then execute with the discovered port number.

**Comment by akoshelev** [comment]
I like both suggestions, making server pick a port and report it to the test program feels a bit more safe though

**Comment by andyleiserson** [comment]
The additional complication for our use case is that each helper needs to be aware of the others' URLs. So if we want the server to pick a port on startup and output the port, then we also need to modify the server to configure the peer URLs in a separate step after the runner has collected ports from all three peers, rather than reading network.toml on startup.

**Comment by martinthomson** [comment]
Oh yeah, that is awkward.  The usual trick I see there is SIGUSR1 prompting the server to re-read its configuration.  Which is maybe worthwhile as a feature in general, but quite a bit more annoying to rig up.
