### ISSUE TITLE
Build and publish sample helper images

### ISSUE THREAD

**Issue by martinthomson** [private-attribution/ipa#691]
For IPA, what you would do is... One image contains all the built code and the three helper configs.  Publish that build image to a local registry (line 43-44 in the example below).  Then you have three separate helper images that build based on that image and pull the binary and just their own config.

We should make clear in documentation that the private keys for these is not secure.  Having overrides for config might make it easy to setup custom configurations.

https://github.com/martinthomson/i-d-template/blob/main/.github/workflows/docker.yml has a worked CI example.

**Comment by akoshelev** [comment]
I am not sure if there is a difference between organizational repositories and personal ones. Have you tried to connect the package to the repository? https://docs.github.com/en/packages/learn-github-packages/connecting-a-repository-to-a-package

**Comment by richajaindce** [comment]
I was able to push a docker image using instructions on that link here: https://github.com/richajaindce?tab=packages&repo_name=raw-ipa
However, I am still unable to push a docker image using Github actions. It fails with error
"Error: buildx failed with: ERROR: failed to solve: failed to push ipa:latest: failed to authorize: failed to fetch oauth token: unexpected status: 401 Unauthorized"
Link to a run: https://github.com/richajaindce/raw-ipa/actions/runs/5308293077/jobs/9607616545
GITHUB_TOKEN permissions seem to be ok with permission to read and write a package.

**Comment by akoshelev** [comment]
after pushing the initial version to main, our CI is broken: https://github.com/private-attribution/ipa/actions/runs/5336458972/jobs/9675341666

```bash
  Downloaded tempfile v3.6.0
#13 3.604 warning: File system loop found: /proc/self/task/6/fd/16 points to an ancestor /
#13 3.604 warning: File system loop found: /proc/self/task/6/fd/17 points to an ancestor /proc
#13 3.604 warning: File system loop found: /proc/self/task/6/fd/18 points to an ancestor /proc/self
#13 3.604 warning: File system loop found: /proc/self/task/6/fd/19 points to an ancestor /proc/self/task
#13 3.605 warning: File system loop found: /proc/self/task/6/fd/20 points to an ancestor /proc/self/task/6
#13 3.605 warning: File system loop found: /proc/self/task/6/fd/21 points to an ancestor /proc/self/task/6/fd
#13 3.605 warning: File system loop found: /proc/self/task/6/cwd points to an ancestor /
#13 3.605 warning: File system loop found: /proc/self/task/6/root points to an ancestor /
#13 3.606 warning: File system loop found: /proc/self/fd/16 points to an ancestor /
#13 3.606 warning: File system loop found: /proc/self/fd/17 points to an ancestor /proc
#13 3.606 warning: File system loop found: /proc/self/fd/18 points to an ancestor /proc/self
#13 3.606 warning: File system loop found: /proc/self/fd/19 points to an ancestor /proc/self/fd
#13 3.607 warning: File system loop found: /proc/self/cwd points to an ancestor /
#13 3.607 warning: File system loop found: /proc/self/root points to an ancestor /
#13 3.607 warning: File system loop found: /proc/thread-self/fd/16 points to an ancestor /
#13 3.608 warning: File system loop found: /proc/thread-self/fd/17 points to an ancestor /proc
#13 3.608 warning: File system loop found: /proc/thread-self/fd/18 points to an ancestor /proc/thread-self
#13 3.608 warning: File system loop found: /proc/thread-self/fd/19 points to an ancestor /proc/thread-self/fd
```


and then it eventually times out. I wonder if it is happening because we are building the image from `/`?

**Comment by martinthomson** [comment]
Yikes.  The build should run from the workspace directory.  Though I've found that it is better to point at a directory with the `context` attribute to the build.  I'm a little surprised, but it seems to default to "/".

**Comment by akoshelev** [comment]
@martinthomson this seems to be fixed now. Should we close this?

**Comment by martinthomson** [comment]
Yes
