### ISSUE TITLE
Support variable-size generation from PRSS

### ISSUE THREAD

**Issue by andyleiserson** [private-attribution/ipa#884]
Currently PRSS generation is fixed size in that it always consumes 128 bits of entropy. The actual value generated can be smaller (by discarding some of the entropy), and with effort larger (by instantiating another PRG to expand the entropy). Generation of small values is currently wasteful, in that it pays to generate bits from an AES PRG that it doesn't need. Generation of larger values is becoming necessary to support Curve25519 and vectorization.

This was originally suggested in https://github.com/private-attribution/ipa/issues/812#issuecomment-1825019292, and there is some discussion in https://github.com/private-attribution/ipa/pull/877/files#r1416577716.

**Comment by andyleiserson** [comment]
Copying @danielmasny's comment from https://github.com/private-attribution/ipa/pull/877#discussion_r1423045616:

> isn't that reimplementing Distribution with the only difference using a seed instead of a RNG? We could also consider having PRSS returning an RNG (and implement an RNG that panics when we request too many bits). This would allow us to use the standard rust conventions.
>
> Here with panic, I mean debug panic such that we could identify when we requesting AES evaluations for identical inputs twice.

**Comment by andyleiserson** [comment]
> Isn't that reimplementing Distribution with the only difference using a seed instead of a RNG?

It never does any expansion of the entropy provided. i.e. if we're generating a BA256, the input type is `[u128; 2]`. If we're generating a hypothetical BA1024, the input type would be `[u128; 8]`, and so on.

> This would allow us to use the standard rust conventions.

Yeah, it would be nice to do that. That's what I was thinking about when I wrote "I don't see it as having any fundamental difference from rand's `Distribution<Standard>`" in the description of #877. Although I later reassessed and decided that I do see a fundamental difference: stream-style consumption or entropy (APIs that fill an arbitrary slice with random bits or that can be called any number of times) vs. consumption of a fixed amount of entropy. I guess we could implement in terms of "panic if it requests too many bits", but I think I would prefer that the amount of entropy be exposed explicitly (via the size of the array) rather than just taking an index as an argument, which seems like it has the same drawbacks as the `2*index` approach, but with less visibility of the number of indexes that are going to be used.

**Comment by andyleiserson** [comment]
I'll mention an idea I had here, although I haven't spent any time exploring the details. The idea is to make some sort of family of PrssIndex types to keep track of the different rate of index consumption. Kind of like RecordId, but PrssIndex would be a family with one type for indexing pseudo-randomness in chunks of 128 bits, a different type for indexing in chunks of 256 bits, etc.

**Comment by danielmasny** [comment]
shouldn't solve something like $index<<64$ (rather than $2\cdot index$) solve our issue? I think index or record id is only 64 bit and we are not going to request $128\cdot 2^{64}$ bits from the PRG. We could still debug panic just in case :)

**Comment by martinthomson** [comment]
There are usage constraints on PRSS that we need to be careful of if we start sampling a lot.  Not a big deal until we get past $2^48$, but if we do, we'd want to be careful.  The PrssIndex idea is worth exploring on that basis as it can help us avoid drawing too heavily on the PRSS.  See https://martinthomson.github.io/ipa-id/draft-thomson-ppm-prss.html#name-usage-limit-analysis for a fairly lightweight usage limit analysis.
