### ISSUE TITLE
Compact gate for the malicious IPA is broken

### ISSUE THREAD

**Issue by akoshelev** [private-attribution/ipa#921]
Currently failing with

```
thread 'tokio-runtime-worker' panicked at ipa-core/src/protocol/attribution/mod.rs:429:10:
Invalid state transition: 2182 -> current_credit_or_credit_update
```

reproducible in integration tests only, when setting the input size to 100. 10 is too small to hit the bad path, but we can't run anything at scale

**Comment by akoshelev** [comment]
steps to reproduce:

1. Change [this](https://github.com/private-attribution/ipa/blob/fd307243498fdbe889fa51d05a22b2732bd56382/ipa-core/tests/common/mod.rs#L206) to 100
2. Run compact gate tests: `cargo test --no-default-features --features "cli web-app real-world-infra test-fixture compact-gate"`

**Comment by benjaminsavage** [comment]
I think #927 addresses this.

**Comment by akoshelev** [comment]
Now it works for 100 rows, but fails for 100k

```
thread 'tokio-runtime-worker' panicked at ipa-core/src/protocol/basics/mul/malicious.rs:18:10:
Invalid state transition: 2274 -> duplicate_multiply
```

**Comment by benjaminsavage** [comment]
This makes sense.

The steps of old IPA are dependent upon the total number of rows. To be specific, the "interaction pattern" stuff that controls the binary tree approach is the part that is dependent.
So in general, the number of passes is O(log(n)) records.

**Comment by richajaindce** [comment]
Based on "ancient" commit we had upto depth31 and that must be the reason for it to work. Will add it back. https://raw.githubusercontent.com/private-attribution/ipa/2763bbf76fd2e7f11e2641c2e66d08c0af3d9cb8/ipa-core/src/protocol/step/steps.txt

**Comment by akoshelev** [comment]
I ran this on 100k input and it worked so I think that this issue can be closed now.
One thing that I noticed is that the order of step is different depending on whether we run `collect_steps` with single thread or multiple threads. `steps.txt` generated using only one thread causes mutli-thread IPA to crash
