### ISSUE TITLE
Test `parallel_join_forget_is_not_safe` sometimes hangs

### ISSUE THREAD

**Issue by andyleiserson** [private-attribution/ipa#986]
Here is one instance: https://github.com/andyleiserson/ipa/actions/runs/8351946541/job/22861212660

I seem to be able to reproduce locally, as well, although I've had mixed success so I'm not sure if there could be environmental factors that affect whether it will reproduce.

Looking at the test, one thing I'm not sure about is whether tokio yield_now is guaranteed to do something fair (or even anything at all). In which case the test thread might be able to complete 100 loops before the main thread has dropped anything.

**Comment by akoshelev** [comment]
we could replace `yield_now` with `tokio::sleep(1ms)` and see if it fixes it
